(cl:defpackage darknet_ros_msgs-msg
  (:use )
  (:export
   "<BOUNDINGBOX>"
   "BOUNDINGBOX"
   "<BOUNDINGBOXES>"
   "BOUNDINGBOXES"
   "<CHECKFOROBJECTSACTION>"
   "CHECKFOROBJECTSACTION"
   "<CHECKFOROBJECTSACTIONFEEDBACK>"
   "CHECKFOROBJECTSACTIONFEEDBACK"
   "<CHECKFOROBJECTSACTIONGOAL>"
   "CHECKFOROBJECTSACTIONGOAL"
   "<CHECKFOROBJECTSACTIONRESULT>"
   "CHECKFOROBJECTSACTIONRESULT"
   "<CHECKFOROBJECTSFEEDBACK>"
   "CHECKFOROBJECTSFEEDBACK"
   "<CHECKFOROBJECTSGOAL>"
   "CHECKFOROBJECTSGOAL"
   "<CHECKFOROBJECTSRESULT>"
   "CHECKFOROBJECTSRESULT"
  ))

