; Auto-generated. Do not edit!


(cl:in-package darknet_ros_msgs-msg)


;//! \htmlinclude CheckForObjectsFeedback.msg.html

(cl:defclass <CheckForObjectsFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CheckForObjectsFeedback (<CheckForObjectsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CheckForObjectsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CheckForObjectsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name darknet_ros_msgs-msg:<CheckForObjectsFeedback> is deprecated: use darknet_ros_msgs-msg:CheckForObjectsFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CheckForObjectsFeedback>) ostream)
  "Serializes a message object of type '<CheckForObjectsFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CheckForObjectsFeedback>) istream)
  "Deserializes a message object of type '<CheckForObjectsFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CheckForObjectsFeedback>)))
  "Returns string type for a message object of type '<CheckForObjectsFeedback>"
  "darknet_ros_msgs/CheckForObjectsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CheckForObjectsFeedback)))
  "Returns string type for a message object of type 'CheckForObjectsFeedback"
  "darknet_ros_msgs/CheckForObjectsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CheckForObjectsFeedback>)))
  "Returns md5sum for a message object of type '<CheckForObjectsFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CheckForObjectsFeedback)))
  "Returns md5sum for a message object of type 'CheckForObjectsFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CheckForObjectsFeedback>)))
  "Returns full string definition for message of type '<CheckForObjectsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CheckForObjectsFeedback)))
  "Returns full string definition for message of type 'CheckForObjectsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CheckForObjectsFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CheckForObjectsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CheckForObjectsFeedback
))
